## Часть 3: Знакомство с numpy.  Работа с векторами и матрицами.

Автор: Потанин Марк, mark.potanin@phystech.edu

`NumPy` — это расширение языка Python, добавляющее поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых математических функций для операций с этими массивами.

Основной элемент NumPy – __массивы__, о которых можно думать как о векторах (одноразмерные массивы) и матрицах (двуразмерные массивы).

Подключить numpy к нашей среде разработки можно с помощью команды `import numpy as np`. В дальнейшем будем обрщаться к объектам `numpy` через `np`, для краткости. 

In [165]:
#%pip install numpy

In [167]:
import numpy as np

Главной особенностью `numpy` является объект `array`, он же массив. Массивы схожи со списками в python, исключая тот факт, что элементы массива должны иметь одинаковый тип данных, как `float` и `int`. С массивами можно проводить числовые операции с большим объемом информации в разы быстрее и, главное, намного эффективнее чем со списками.


Массив можно создать из списка при помощи функции `np.array()`.

In [169]:
vec1 = np.array([1, 2, 3])

In [171]:
vec1

array([1, 2, 3])

In [172]:
type(vec1)

numpy.ndarray

Метод `shape` позволяет получить размерность массива, в данном случае – это вектор 3х1.

In [173]:
vec1.shape

(3,)

Создние матрицы.

In [174]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

In [175]:
matrix1.shape

(2, 3)

Матрица размера 2х3

In [176]:
matrix1.shape

(2, 3)

Функция `np.zeros()` позволяет создать массив заданного размера, заполненный нулями.

In [177]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [178]:
np.zeros((45,49,50 ,100)).shape

(45, 49, 50, 100)

Аналогичная функция `np.ones()` создает массив заданного размера, заполненный единицами.

In [180]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Функция `np.full()` создает массив заполненный указанным элементом. В примере мы создаем массив размером 3x5, заполненый значением 3.14.

In [181]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Функция `np.arange()` позволяет создать последовательность чисел. Мы указываем начало, конец, и шаг последовательности.

In [182]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [183]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Есть похожая функция `np.linspace()`. В ней мы указываем начало последовательности, ее конец, и количество точек в последовательности. Она автоматически разбивает указанный отрезок на интервалы.

In [184]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

#### Массивы случайных чисел.

Можно создавать массивы со случайными числами при помощи функции `rand()` модуля `random`.

In [186]:
np.random.rand(4)

array([0.53735771, 0.90685481, 0.81596003, 0.324556  ])

Для получения случайных чисел из нормального распределения используем функцию `randn()` из модуля `random`. Для создания матрицы случайных чисел надо передать функции два числа.

In [187]:
np.random.randn(5)

array([-1.12160914,  2.55830247, -1.03326146,  0.78152076,  0.39171662])

In [188]:
np.random.randn(5,3)

array([[ 2.64730354, -0.51626607,  1.37031487],
       [ 0.48690986, -1.38799246, -0.21649734],
       [ 0.55479866,  0.24367919, -0.01510607],
       [ 1.77033114,  0.36856016, -0.04212352],
       [ 1.37513657,  2.23323114, -0.25445135]])

Создаем массив размером 3х3 случайных целых чисел в промежутке (0, 10):

In [190]:
np.random.randint(0, 10, (3, 3))

array([[6, 6, 3],
       [0, 2, 9],
       [4, 4, 0]])

Создаем единичную матрицу размером 3х3:

In [191]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Индексация массива: доступ к отдельным элементам.

In [192]:
x = np.arange(20)

In [193]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Индексация как для стандартных списков Python.

In [194]:
x[0]

np.int64(0)

In [195]:
x[5]

np.int64(5)

In [196]:
x1=np.random.randint(0, 10, (3, 3))

In [197]:
x1

array([[9, 2, 9],
       [0, 3, 1],
       [4, 5, 0]])

In [200]:
x1[0][0]

np.int64(9)

In [201]:
x1[2][1]

np.int64(5)

Массивы можно изменять.

In [202]:
x1[1][2] = 100

In [203]:
x1

array([[  9,   2,   9],
       [  0,   3, 100],
       [  4,   5,   0]])

Так же как со списками, удобно делать срезы массивов.

In [204]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [205]:
x[:5] # первые пять элементов

array([0, 1, 2, 3, 4])

In [206]:
x[4:7] 

array([4, 5, 6])

In [207]:
x[::4] # каждый второй элемент

array([ 0,  4,  8, 12, 16])

In [208]:
x[::-2] # все элементы в обратном порядке

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [209]:
x2=np.random.randint(0, 10, (5, 5))

In [210]:
x2

array([[5, 9, 3, 3, 1],
       [8, 3, 0, 1, 8],
       [8, 5, 9, 8, 0],
       [2, 0, 5, 1, 1],
       [0, 3, 8, 1, 2]])

In [211]:
x2[:2, :3] # две строки и три столбца

array([[5, 9, 3],
       [8, 3, 0]])

In [212]:
x2[:3, ::2] # все строки, каждый второй столбец

array([[5, 3, 1],
       [8, 0, 8],
       [8, 9, 0]])

Доступ к строкам и столбцам массива происходит с помощью среза. И имеет вид `x[:,num_col]` для выбора столбца с номером `num_col`, `x[:,num_row]` для выбора строки с номером `num_row`.

In [213]:
x2[:, 0] # первый столбец массива

array([5, 8, 8, 2, 0])

In [214]:
x2[0, :] # первая строка массива - эквивалентно x2[0]

array([5, 9, 3, 3, 1])

In [215]:
x2[0]

array([5, 9, 3, 3, 1])

In [216]:
x2[2,2]

np.int64(9)

#### Изменение формы массивов.

Изменить массив в желаемую форму поможет функция `reshape`. Она принимает на вход размерность нового массива, который мы хотим получить.

In [218]:
grid = np.arange(1, 10)

In [219]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
np.arange(1, 10).reshape(3, 3) # поместить числа от 1 до 10 в таблицу 3х3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Слияние и разбиение массивов.

Метод `np.concatenate` принимает на вход список массивов, и склеивает их.

In [223]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])


Можно объединить более двух массивов одновременно

In [225]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

Для объединения двух массивов можно также использовать `np.concatenate`.

In [226]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [227]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [228]:
np.concatenate([grid, grid]) # слияние по первой оси координат


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [229]:
np.concatenate([grid, grid], axis=1) # слияние по второй оси координат(с индексом 0)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Для работы с массивами с различающимися измерениями удобнее и понятнее использовать функции `np.vstack` (вертикальное объединение) и `np.hstack` (горизонтальное объединение).

In [231]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([grid,x]) # объединяет массивы по вертикали

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [232]:
y = np.array([[99],
             [99]])
np.hstack([grid, y]) # объединяе массивы по горизонтали

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Выполнение вычислений над массивами.


NumPy поддерживает векторизованные операции - операция с массивом, которая применяется ко всем элементам массива. Это, наверное, одна из главных фишек NumPy.

Пример

In [233]:
[2,3,4]*10

[2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 3,
 4]

In [234]:
np.array([2,3,4])*2

array([4, 6, 8])

Здесь нас ждем ошибка. Потому как питон не понимает, как можно разделить число на список.

In [236]:
1/[2,3,4]

TypeError: unsupported operand type(s) for /: 'int' and 'list'

NumPy же справляется с этой задачей.

In [237]:
1/np.array([2,3,4])

array([0.5       , 0.33333333, 0.25      ])

Можно складывать массивы поэелементно.

In [238]:
[1,2,3]+[3,4,2]

[1, 2, 3, 3, 4, 2]

Можно складывать массивы поэелементно.

In [240]:
x = np.arange(5)
y = np.arange(1, 6)

In [241]:
x

array([0, 1, 2, 3, 4])

In [242]:
y

array([1, 2, 3, 4, 5])

In [243]:
x+y

array([1, 3, 5, 7, 9])

Работа с многомерными массивами.

In [244]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [245]:
x = np.arange(9).reshape((3, 3))

In [246]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [247]:
x**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [248]:
%%time
x = np.arange(100000)**700

CPU times: user 1.15 ms, sys: 959 μs, total: 2.11 ms
Wall time: 1.02 ms


In [249]:
%%time
x = [i**700 for i in range(100000)]

CPU times: user 2.54 s, sys: 25.3 ms, total: 2.57 s
Wall time: 2.6 s


#### Обзор универсальных функций.

In [250]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # деление с округлением в меньшую сторону

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


Существует также унарная универсальная функция для операции изменения знака, оператор `**` для возведения в степень и оператор `%` для деления по модулю. Все как у обычных чисел в питоне, только теперь мы можем легко применять эти операции к целому массиву данных.

In [251]:
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)

-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


#### Далее мы посмотрим на основные математические функции, которые могут применяться к массивам.

In [252]:
x = np.array([-2, -1, 0, 1, 2])

Абсолютное значение.


In [253]:
np.abs(x)

array([2, 1, 0, 1, 2])

Тригонометрические функции.

In [82]:
np.pi?

Type:        float
String form: 3.141592653589793
Docstring:   Convert a string or number to a floating point number, if possible.

In [83]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [254]:
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]



Показательные функции и логарифмы.

In [255]:
x = [1, 2, 3]
print("x    =", x)
print("e^x  =", np.exp(x))
print("2^x  =", np.exp2(x))
print("3^x  =", np.power(3, x))

x    = [1, 2, 3]
e^x  = [ 2.71828183  7.3890561  20.08553692]
2^x  = [2. 4. 8.]
3^x  = [ 3  9 27]


In [257]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)    =", np.log2(x))
print("log10(x)    =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)    = [0.         1.         2.         3.32192809]
log10(x)    = [0.         0.30103    0.60205999 1.        ]


Суммирование значений из массива.

In [258]:
L = np.random.randint(10000,size=(10,10))

In [259]:
L

array([[ 398, 8939, 1851, 1559, 1680, 5550,  584, 9511, 4584,    9],
       [ 710, 4610,  207, 9705, 8640, 4715, 4700,    2, 4224, 7767],
       [5442, 4799, 6961, 8980, 4077, 4198, 3446,   69, 1965, 9818],
       [1155, 6048, 6872, 7305,  984, 9474, 1186, 7824, 7207, 4565],
       [ 145, 8861, 8622, 2750, 9148,  982, 8395, 8711, 8580, 1979],
       [5648, 5777, 5479, 3129, 5875, 2007,  685, 7069, 7933, 3673],
       [9895, 2489, 1195, 2686,  934, 3309, 5540, 9769, 3448, 8447],
       [5336, 3517, 1582, 1634,  978, 7661, 3879, 9291, 2217, 9088],
       [8918, 9045, 5090, 1695, 6773,  340, 9345, 6846, 3658, 6135],
       [5525, 3945,  563, 9857, 4255, 1268, 9939, 8660, 6773, 3309]])

In [261]:
L

array([[ 398, 8939, 1851, 1559, 1680, 5550,  584, 9511, 4584,    9],
       [ 710, 4610,  207, 9705, 8640, 4715, 4700,    2, 4224, 7767],
       [5442, 4799, 6961, 8980, 4077, 4198, 3446,   69, 1965, 9818],
       [1155, 6048, 6872, 7305,  984, 9474, 1186, 7824, 7207, 4565],
       [ 145, 8861, 8622, 2750, 9148,  982, 8395, 8711, 8580, 1979],
       [5648, 5777, 5479, 3129, 5875, 2007,  685, 7069, 7933, 3673],
       [9895, 2489, 1195, 2686,  934, 3309, 5540, 9769, 3448, 8447],
       [5336, 3517, 1582, 1634,  978, 7661, 3879, 9291, 2217, 9088],
       [8918, 9045, 5090, 1695, 6773,  340, 9345, 6846, 3658, 6135],
       [5525, 3945,  563, 9857, 4255, 1268, 9939, 8660, 6773, 3309]])

In [265]:
big_array = np.random.rand(1000000)

In [266]:
big_array

array([0.03283633, 0.98698847, 0.96710835, ..., 0.08790523, 0.73428642,
       0.60580074])

In [267]:
np.sum(big_array)

np.float64(499795.7843223296)

Минимум и максимум.

In [268]:
np.min(big_array)

np.float64(5.288667792591184e-07)

In [269]:
np.max(big_array)

np.float64(0.9999997879207114)

Агрегирование по столбцу или строке - один из часто применяемых видов операций агрегирования. Пусть имеются какие-либо данные, находящиеся в двумерном массиве.

In [270]:
M = np.random.random((3, 4))

In [271]:
M

array([[0.75209227, 0.66879684, 0.62974166, 0.88615706],
       [0.88666076, 0.75310343, 0.69335287, 0.26091975],
       [0.8967608 , 0.80965696, 0.97019383, 0.89411209]])

In [272]:
M

array([[0.75209227, 0.66879684, 0.62974166, 0.88615706],
       [0.88666076, 0.75310343, 0.69335287, 0.26091975],
       [0.8967608 , 0.80965696, 0.97019383, 0.89411209]])

In [273]:
np.sum(M)

np.float64(9.101548330410433)

По умолчанию все функции агрегирования NumPy возвращают сводный показатель по всему массиву. Но можно указать ось, по которой вычисляется сводный показатель. Например, можно найти минимальное значение каждого из столбцов, указав axis=0.

In [274]:
np.min(M,axis=1) # Функция возвращает четыре значения, соответствующие четырем столбцам чисел.

array([0.62974166, 0.26091975, 0.80965696])


Для поиска максимального значения в строке можно использовать axis=1:

In [275]:
np.max(M,axis=1) # Функция возвращает три значения, соответствующие трем строкам чисел.

array([0.88615706, 0.88666076, 0.97019383])

Еще одно замечание - необязательно вызывать функцию аггрегирования напрямую из NumPy. Пусть `M` - некоторый массив (матрица например), тогда вместо `np.max()` можно написать `M.max()` - так тоже будет работать.

In [276]:
np.max(M)

np.float64(0.9701938302590221)

In [277]:
M.max()

np.float64(0.9701938302590221)

In [278]:
M.min()

np.float64(0.2609197499111894)

Есть много других функций агрегирования.

In [279]:
x = np.random.rand(1, 20)
x

array([[0.51933808, 0.02115228, 0.4582244 , 0.97703755, 0.45360401,
        0.66896954, 0.40783347, 0.20028067, 0.78681704, 0.60596837,
        0.11162978, 0.34473593, 0.8279693 , 0.55050227, 0.34990595,
        0.11809544, 0.35835421, 0.95966247, 0.33206563, 0.22390493]])

In [281]:
x.prod() # произведение элементов

np.float64(1.077131362453613e-09)

In [282]:
x.mean() # среднее значение элементов

np.float64(0.46380256493440825)

In [283]:
x.std() # стандартное отклонение

np.float64(0.268748261936793)

In [284]:
x.var() # дисперсия

np.float64(0.0722256282940471)

In [285]:
np.median(x) # медиана элементов

np.float64(0.4307187392388989)

#### Транслирование.

Транслирование - применение универсальных функций (сложение, вычитание, умножение и т.д.) к массивам различного размера.

Для массивов одного размера математические операции выполняются поэлементно.

In [286]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

Транслирование дает возможность выполнять подобные виды бинарных операций над массивами различных размеров, например, можно легко прибавить скалярное значение (рассматривая его как нульмерный массив) к массиву:

In [288]:
a + 5

array([5, 6, 7])

Транслирование в массивах большей размерности:

In [289]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [290]:
a

array([0, 1, 2])

In [291]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Здесь одномерный массив `а` растягивается (транслируется) на второе измерение, чтобы соответствовать форме массива `М`.

Пример использования транслирования на практике - центрирование массива.

In [292]:
x = np.random.random((10, 3))
x

array([[0.52039111, 0.74926056, 0.41975866],
       [0.87232494, 0.11533397, 0.75333809],
       [0.20489028, 0.90200417, 0.69704352],
       [0.92518816, 0.9610455 , 0.89202109],
       [0.2408414 , 0.59494222, 0.63423755],
       [0.61555932, 0.2664431 , 0.74065609],
       [0.60662361, 0.8141144 , 0.57531854],
       [0.37875278, 0.38218353, 0.64292752],
       [0.38735036, 0.56119594, 0.56217663],
       [0.82514271, 0.23769458, 0.22190236]])

In [293]:
xmean = x.mean(axis=0)
xmean

array([0.55770647, 0.5584218 , 0.613938  ])

Можно отцентрировать массив вычитанием среднего значения (это операция транслирования):

In [294]:
x_centered = x - xmean
x_centered

array([[-0.03731536,  0.19083876, -0.19417935],
       [ 0.31461848, -0.44308783,  0.13940008],
       [-0.35281619,  0.34358237,  0.08310551],
       [ 0.3674817 ,  0.4026237 ,  0.27808309],
       [-0.31686507,  0.03652043,  0.02029954],
       [ 0.05785285, -0.29197869,  0.12671809],
       [ 0.04891714,  0.2556926 , -0.03861946],
       [-0.17895369, -0.17623827,  0.02898951],
       [-0.17035611,  0.00277414, -0.05176138],
       [ 0.26743625, -0.32072721, -0.39203564]])

#### Сравнения и булевы маски.

In [296]:
x = np.array([1, 2, 3, 4, 5])

In [298]:
x < 3

array([ True,  True, False, False, False])

In [299]:
x != 3

array([ True,  True, False,  True,  True])

In [300]:
x == 3

array([False, False,  True, False, False])

In [301]:
x = np.random.randint(10, size=(3, 4))
x

array([[6, 7, 0, 2],
       [5, 0, 9, 2],
       [7, 0, 8, 8]])

In [302]:
x < 6

array([[False, False,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

Для подсчета количества элементов `True` в булевом массиве можно использовать `np.count_nonzero`.

In [304]:
np.count_nonzero(x<6)

6

In [305]:
x

array([[6, 7, 0, 2],
       [5, 0, 9, 2],
       [7, 0, 8, 8]])

In [306]:
x<6

array([[False, False,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [307]:
np.sum(x < 6) # подсчет количества элементов в массиве, значения которых меньше 6 (False == 0, True == 1)

np.int64(6)

`np.any()` позволяет проверить условие присутствия в массиве значений больше какого то числа, например 8 (проверить что хотя бы одно число в массиве больше 8).

In [308]:
np.any(x > 8) 

np.True_

`np.all()` позволяет проверить условие того, что все элементы массива больше какого то числа, например 1.

In [309]:
np.all(x > 1) 


np.False_

In [310]:
np.any(x == 0)

np.True_

Функции `np.any()` и `np.all()` также можно было использовать по конкретным осям.

In [311]:
np.all(x > 3, axis=0)

array([ True, False, False, False])

In [312]:
np.all(x > 3, axis=1)

array([False, False, False])

Булевы массивы как маски.

In [313]:
x

array([[6, 7, 0, 2],
       [5, 0, 9, 2],
       [7, 0, 8, 8]])

In [314]:
x<4

array([[False, False,  True,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

Чтобы выбрать нужные значения из массива, достаточно просто проиндексировать исходный массив `x` по этому булеву массиву. Такое действие носит название наложение маски или маскирование:

In [318]:
x[x < 4]

array([0, 2, 0, 2, 0])

#### Сортировка массивов.

Чтобы получить отсортированную версию массива, можно использовать функцию `np.sort`.

In [319]:
x = np.array([2, 1, 4, 3, 5])

In [320]:
x

array([2, 1, 4, 3, 5])

In [321]:
np.sort(x)

array([1, 2, 3, 4, 5])

Функция `argsort` возвращает индексы отсортированных элементов.

In [322]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)

In [323]:
i

array([1, 0, 3, 2, 4])

Можно сортировать матрицы по строкам и столбцам.

In [324]:
X = np.random.randint(0, 10, (4, 6))

In [325]:
X

array([[3, 8, 3, 0, 1, 1],
       [6, 8, 1, 4, 0, 5],
       [4, 8, 3, 7, 7, 6],
       [1, 2, 1, 3, 1, 5]])

Сортировка всех столбцов массива X.

In [326]:
np.sort(X, axis=0)

array([[1, 2, 1, 0, 0, 1],
       [3, 8, 1, 3, 1, 5],
       [4, 8, 3, 4, 1, 5],
       [6, 8, 3, 7, 7, 6]])

Сортировка всех строк массива X.

In [327]:
np.sort(X, axis=1)

array([[0, 1, 1, 3, 3, 8],
       [0, 1, 4, 5, 6, 8],
       [3, 4, 6, 7, 7, 8],
       [1, 1, 1, 2, 3, 5]])

Все строки или столбцы массива рассматриваются как отдельные массивы, так что любые возможные взаимосвязи между значениями строк или столбцов будут утеряны.

C помощью функций `np.dot()` или `np.matmul()` можно производить произведение матриц. 


In [328]:
matrix_1 = np.array([[7, 4, 1], 
                     [1, 2, 2]])
matrix_2 = np.array([[3, 2], 
                     [1, 1], 
                     [0, 4]])

In [329]:
np.dot(matrix_1,matrix_2)

array([[25, 22],
       [ 5, 12]])

#### Многомерные массивы.

In [331]:
x = np.random.randint(0,10,size=(3,4,8))

In [332]:
x

array([[[6, 6, 6, 8, 2, 7, 0, 9],
        [1, 0, 7, 4, 9, 9, 6, 0],
        [8, 5, 8, 1, 2, 6, 1, 4],
        [1, 9, 0, 1, 0, 5, 0, 8]],

       [[5, 3, 6, 8, 9, 6, 5, 0],
        [4, 1, 0, 8, 9, 3, 7, 1],
        [2, 1, 4, 1, 9, 1, 4, 9],
        [1, 6, 8, 2, 7, 4, 9, 9]],

       [[8, 4, 1, 8, 6, 9, 7, 5],
        [7, 8, 4, 9, 9, 9, 9, 1],
        [5, 7, 0, 1, 6, 3, 8, 4],
        [7, 9, 2, 9, 9, 2, 7, 0]]])

In [333]:
x.shape

(3, 4, 8)

#### Операции линала

In [349]:
x = np.random.randint(1,5, size= (4,4))

In [350]:
x

array([[1, 2, 2, 4],
       [3, 3, 3, 1],
       [2, 3, 4, 4],
       [1, 2, 3, 1]])

In [351]:
np.linalg.det(x)

np.float64(8.000000000000002)

In [352]:
y = np.linalg.inv(x)

In [353]:
y

array([[-1.   ,  0.25 ,  1.25 , -1.25 ],
       [ 2.   ,  0.5  , -2.5  ,  1.5  ],
       [-1.   , -0.375,  1.125, -0.125],
       [-0.   , -0.125,  0.375, -0.375]])

In [354]:
print(x.dot(y))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00 -1.11022302e-16  0.00000000e+00  1.00000000e+00]]


In [355]:
eigenval, eigenvec = np.linalg.eig(x)

In [356]:
print(eigenval)
print(eigenvec)

[10.01089434+0.j          0.657136  +0.j         -0.83401517+0.72145538j
 -0.83401517-0.72145538j]
[[-0.42374814+0.j          0.09260185+0.j          0.67815666+0.j
   0.67815666-0.j        ]
 [-0.51146246+0.j         -0.83998838+0.j         -0.64771502-0.11859493j
  -0.64771502+0.11859493j]
 [-0.64628345+0.j          0.5112465 +0.j          0.20860803-0.07768605j
   0.20860803+0.07768605j]
 [-0.37571447+0.j          0.15643348+0.j         -0.0913839 +0.22045543j
  -0.0913839 -0.22045543j]]
